import { cleanup, render as rtlRender, screen, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const { replaceMock, searchMock } = vi.hoisted(() => ({ replaceMock: vi.fn(), searchMock: { value: null as string | null } }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace: replaceMock }), useSearchParams: () => ({ get: () => searchMock.value }) }));
import { LoginForm } from "./login/login-form";
import { RegisterForm } from "./register/register-form";
const fetchMock = vi.fn<typeof fetch>();
async function fillLogin(user: ReturnType<typeof userEvent.setup>, email = "user@example.test") { await user.type(screen.getByLabelText("E-mail"), email); await user.type(screen.getByLabelText("Senha"), "Password1!"); await user.click(screen.getByRole("button", { name: "Entrar" })); }
function render(ui: ReactNode) {
  return rtlRender(<QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}>{ui}</QueryClientProvider>);
}
describe("formulários BFF same-origin", () => {
  beforeEach(() => { vi.stubGlobal("fetch", fetchMock); fetchMock.mockReset(); replaceMock.mockReset(); searchMock.value = null; });
  afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
  it("login ROLE_USER confirma a sessão antes de navegar para returnTo seguro", async () => { searchMock.value = "/carteira/posicoes"; fetchMock.mockResolvedValueOnce(new Response(null, { status: 204 })).mockResolvedValueOnce(new Response(JSON.stringify({ id: "u1", nome: "Pessoa", email: "user@example.test", role: "ROLE_USER", ativo: true }), { status: 200, headers: { "Content-Type": "application/json" } })); render(<LoginForm />); await fillLogin(userEvent.setup()); await waitFor(() => expect(replaceMock).toHaveBeenCalledWith("/carteira/posicoes")); expect(fetchMock.mock.calls.map(([path]) => path)).toEqual(["/api/auth/login", "/api/auth/me"]); });
  it.each([["ROLE_USER", "user@example.test", "/carteira"], ["ROLE_ADMIN", "admin@example.test", "/admin"]] as const)("login %s sem returnTo usa a landing natural", async (role, email, destination) => { fetchMock.mockResolvedValueOnce(new Response(null, { status: 204 })).mockResolvedValueOnce(new Response(JSON.stringify({ id: "u1", nome: "Pessoa", email, role, ativo: true }), { status: 200, headers: { "Content-Type": "application/json" } })); render(<LoginForm />); await fillLogin(userEvent.setup(), email); await waitFor(() => expect(replaceMock).toHaveBeenCalledWith(destination)); });
  it("login usa o destino natural para returnTo externo", async () => { searchMock.value = "https://evil.example"; fetchMock.mockResolvedValueOnce(new Response(null, { status: 204 })).mockResolvedValueOnce(new Response(JSON.stringify({ id: "a1", nome: "Admin", email: "admin@example.test", role: "ROLE_ADMIN", ativo: true }), { status: 200, headers: { "Content-Type": "application/json" } })); render(<LoginForm />); await fillLogin(userEvent.setup(), "admin@example.test"); await waitFor(() => expect(replaceMock).toHaveBeenCalledWith("/admin")); });
it("login mapeia ProblemDetail para pt-BR e preserva somente o correlation ID seguro", async () => { fetchMock.mockResolvedValue(new Response(JSON.stringify({ status: 401, title: "Unauthorized", detail: "raw technical detail" }), { status: 401, headers: { "Content-Type": "application/problem+json", "X-Correlation-ID": "corr-login" } })); render(<LoginForm />); await fillLogin(userEvent.setup()); expect(await screen.findByRole("alert")).toHaveTextContent("E-mail ou senha incorretos."); expect(screen.getByText("Código de suporte: corr-login")).toBeInTheDocument(); expect(document.body).not.toHaveTextContent("raw technical detail"); });
  it("login trata falha de rede de forma segura", async () => { fetchMock.mockRejectedValue(new Error("http://spring.internal")); render(<LoginForm />); await fillLogin(userEvent.setup()); expect(await screen.findByRole("alert")).toHaveTextContent("Não foi possível conectar ao serviço. Verifique sua conexão e tente novamente."); expect(document.body.textContent).not.toContain("spring.internal"); });
  it("cadastro exibe Nome Completo e preserva o payload nome", async () => { fetchMock.mockResolvedValue(new Response(null, { status: 201 })); render(<RegisterForm />); const user = userEvent.setup(); await user.type(screen.getByLabelText("Nome Completo"), "Usuária Valore"); await user.type(screen.getByLabelText("E-mail"), "user@example.test"); await user.type(screen.getByLabelText("Senha"), "Password1!"); await user.click(screen.getByRole("button", { name: "Cadastrar" })); await waitFor(() => expect(replaceMock).toHaveBeenCalledWith("/login")); const request = fetchMock.mock.calls[0][1]; expect(JSON.parse(String(request?.body))).toMatchObject({ nome: "Usuária Valore" }); });
it("cadastro traduz conflito sem exibir o detail do backend", async () => { fetchMock.mockResolvedValue(new Response(JSON.stringify({ status: 409, detail: "raw duplicate constraint" }), { status: 409, headers: { "Content-Type": "application/problem+json", "X-Correlation-ID": "corr-register" } })); render(<RegisterForm />); const user = userEvent.setup(); await user.type(screen.getByLabelText("Nome Completo"), "Usuário"); await user.type(screen.getByLabelText("E-mail"), "user@example.test"); await user.type(screen.getByLabelText("Senha"), "Password1!"); await user.click(screen.getByRole("button", { name: "Cadastrar" })); expect(await screen.findByRole("alert")).toHaveTextContent("Este email já está em uso."); expect(screen.getByText("Código de suporte: corr-register")).toBeInTheDocument(); expect(document.body).not.toHaveTextContent("raw duplicate constraint"); expect(screen.getByLabelText("Nome Completo")).toHaveAttribute("aria-describedby", "register-form-error"); });
  it("mantém formulários no cliente sem importar segredos ou módulos server-only", () => { const sources = ["src/app/login/login-form.tsx", "src/app/register/register-form.tsx", "src/client/auth-form-api.ts"].map((path) => readFileSync(join(process.cwd(), path), "utf8")).join("\n"); expect(sources).not.toMatch(/server\/auth|BACKEND_API_URL|accessToken|Authorization|auth_session|https?:\/\//i); });
});
