package com.carteira.carteiraInvestimento.application.service;
public enum TipoEvento { CADASTRO_USUARIO, LOGIN_SUCESSO, LOGIN_FALHO, USUARIO_INATIVO, ACESSO_NEGADO, ADMIN_INICIAL_CRIADO, DEPOSITO, SAQUE,
	CORRETORA_CRIADA, CORRETORA_EDITADA, CORRETORA_ATIVADA, CORRETORA_DESATIVADA, CORRETORA_COMPLIANCE_REJEITADA }
