package com.carteira.carteiraInvestimento.application.service;
public enum TipoEvento { CADASTRO_USUARIO, LOGIN_SUCESSO, LOGIN_FALHO, USUARIO_INATIVO, ACESSO_NEGADO, ADMIN_INICIAL_CRIADO, DEPOSITO, SAQUE, COMPRA, VENDA,
	CORRETORA_CRIADA, CORRETORA_EDITADA, CORRETORA_ATIVADA, CORRETORA_DESATIVADA, CORRETORA_COMPLIANCE_REJEITADA,
	CAMBIO_INDISPONIVEL, EMAIL_ALTERADO, SENHA_ALTERADA, CONTA_ENCERRADA }
