import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AuthFormError, loginAndConfirm, register } from "./auth-form-api";
const fetchMock = vi.fn<typeof fetch>();
describe("adaptador client same-origin de formulários", () => {
  beforeEach(() => { vi.stubGlobal("fetch", fetchMock); fetchMock.mockReset(); });
  afterEach(() => vi.unstubAllGlobals());
  it("confirma me depois do 204 de login antes de concluir", async () => { fetchMock.mockResolvedValueOnce(new Response(null, { status: 204 })).mockResolvedValueOnce(new Response(JSON.stringify({ id: "u1" }), { status: 200, headers: { "Content-Type": "application/json" } })); await loginAndConfirm({ email: "user@example.test", senha: "Password1!" }); expect(fetchMock).toHaveBeenNthCalledWith(1, "/api/auth/login", expect.objectContaining({ method: "POST", credentials: "same-origin" })); expect(JSON.parse(String(fetchMock.mock.calls[0][1]?.body))).toEqual({ email: "user@example.test", senha: "Password1!" }); expect(fetchMock).toHaveBeenNthCalledWith(2, "/api/auth/me", expect.objectContaining({ method: "GET" })); expect(new Headers(fetchMock.mock.calls[0][1]?.headers).has("authorization")).toBe(false); });
  it("faz cadastro sem confirmar me ou criar login", async () => { fetchMock.mockResolvedValue(new Response(null, { status: 201 })); await register({ nome: "Usuário", email: "user@example.test", senha: "Password1!" }); expect(fetchMock).toHaveBeenCalledTimes(1); expect(fetchMock).toHaveBeenCalledWith("/api/auth/register", expect.objectContaining({ method: "POST" })); });
  it("preserva ProblemDetail e correlation ID seguros", async () => { fetchMock.mockResolvedValue(new Response(JSON.stringify({ status: 401, title: "Não autorizado", detail: "Credenciais inválidas", instance: "/api/auth/login" }), { status: 401, headers: { "Content-Type": "application/problem+json", "X-Correlation-ID": "corr-form" } })); const error = await loginAndConfirm({ email: "user@example.test", senha: "Password1!" }).catch((cause: unknown) => cause); expect(error).toBeInstanceOf(AuthFormError); expect(error).toMatchObject({ kind: "http", status: 401, correlationId: "corr-form", problem: { detail: "Credenciais inválidas" } }); });
  it("classifica rede sem expor detalhes internos", async () => { fetchMock.mockRejectedValue(new Error("ECONNREFUSED http://spring.internal")); const error = await register({ nome: "Usuário", email: "user@example.test", senha: "Password1!" }).catch((cause: unknown) => cause); expect(error).toMatchObject({ kind: "network" }); expect(JSON.stringify(error)).not.toMatch(/spring\.internal|senha|Password1/i); });
});
