"use client";

import { useState } from "react";
import { usePortfolioSummary, usePositions } from "@/client/portfolio-queries";
import { Button } from "@/components/ui/button";
import { EntityLogo } from "./entity-logo";
import { EmptyState, FinancialSkeleton, ProblemDetailAlert } from "./states";
import { Pagination } from "./pagination";
import { AveragePrice, GainLoss, Money, Quantity } from "./values";
import { formatCurrency } from "@/lib/finance/format";

export function PositionsPanel() {
  const [page, setPage] = useState(0); const positions = usePositions(page, 20); const summary = usePortfolioSummary();
  if (positions.isPending || summary.isPending) return <FinancialSkeleton rows={7} label="Carregando posições" />;
  if (positions.isError) return <ProblemDetailAlert error={positions.error} onRetry={() => positions.refetch()} />;
  // A market outage must not hide persisted positions; unavailable market cells are rendered below.
  if (summary.isError) return <PersistedPositions positions={positions.data.items} />;
  if (!positions.data.items.length) return <section className="reference-page"><header className="reference-page__header"><div><h2>Minhas posições</h2><p>Visualize os ativos que compõem sua carteira.</p></div></header><EmptyState title="Sem posições abertas" description="Não há ativos em custódia para exibir." /></section>;
  const valuation = new Map((summary.data?.posicoes ?? []).map((item) => [item.ativoId, item])); const totalPositions = positions.data.totalElements;
  return <section className="reference-page positions-page" aria-labelledby="positions-title"><header className="reference-page__header"><div><h2 id="positions-title">Minhas posições</h2><p>Visualize os ativos que compõem sua carteira, com preços atualizados e desempenho.</p></div></header><div className="positions-metrics"><div className="wealth-hero"><span>Patrimônio total</span><Money value={summary.data.patrimonioTotalBrl} className="wealth-hero__value" /><GainLoss value={summary.data.lucroNaoRealizadoBrl} percentage={summary.data.rentabilidadeNaoRealizadaPercentual} /></div><div className="portfolio-metric"><span>Total investido</span><Money value={summary.data.totalInvestidoBrl} /></div><div className="portfolio-metric portfolio-metric--positive"><span>Resultado / Rentabilidade</span><GainLoss value={summary.data.lucroNaoRealizadoBrl} percentage={summary.data.rentabilidadeNaoRealizadaPercentual} /></div><div className="portfolio-metric"><span>Quantidade de posições</span><strong className="positions-count">{totalPositions}</strong></div></div><section className="reference-table-card"><div className="reference-table-card__heading"><div><h2>Minhas posições <small>({totalPositions})</small></h2><p>Confira seus ativos e acompanhe a performance.</p></div></div><div className="reference-table-wrap"><table className="reference-table"><thead><tr><th>Ativo</th><th>Quantidade</th><th>Preço médio</th><th>Preço atual</th><th>Variação / Resultado</th><th>Valor da posição</th><th>Ação</th></tr></thead><tbody>{positions.data.items.map((position) => { const quote = valuation.get(position.ativoId); return <tr key={position.id}><td><span className="table-asset"><EntityLogo provider={position.logoProvider} reference={position.logoReference} label={position.ticker} /><span><strong>{position.ticker}</strong><small>{position.nome}</small></span></span></td><td><Quantity value={position.quantidade} /></td><td><AveragePrice value={position.precoMedioBrl} /></td><td>{quote?.cotacaoAtual != null ? formatCurrency(quote.cotacaoAtual, position.moeda) : "—"}</td><td>{quote?.lucroNaoRealizadoBrl != null ? <GainLoss value={quote.lucroNaoRealizadoBrl} percentage={quote.rentabilidadePercentual} /> : "Cotação indisponível"}</td><td>{quote?.valorAtualBrl != null ? <Money value={quote.valorAtualBrl} /> : "—"}</td><td><Button variant="secondary" size="sm" onClick={() => window.dispatchEvent(new CustomEvent("valore:sell", { detail: position }))}>Vender</Button></td></tr>; })}</tbody></table></div><footer className="reference-table-card__footer"><span>Total de posições <strong>{totalPositions}</strong></span><span>Valor total das posições <Money value={summary.data.valorPosicoesBrl} /></span></footer></section><Pagination page={positions.data.page} totalPages={positions.data.totalPages} onPageChange={setPage} disabled={positions.isFetching} /></section>;
}

function PersistedPositions({ positions }: { positions: import("@/lib/finance/contracts").Position[] }) {
  return <section className="reference-page positions-page"><header className="reference-page__header"><div><h2>Minhas posições</h2><p>Custódia e preço médio confirmados.</p></div></header><p role="status" className="operation-message">Não foi possível atualizar as cotações agora.</p><section className="reference-table-card"><div className="reference-table-wrap"><table className="reference-table"><thead><tr><th>Ativo</th><th>Quantidade</th><th>Preço médio</th><th>Preço atual</th></tr></thead><tbody>{positions.map(position => <tr key={position.id}><td><strong>{position.ticker}</strong></td><td><Quantity value={position.quantidade} /></td><td><AveragePrice value={position.precoMedioBrl} currency={position.moeda} /></td><td>Indisponível</td></tr>)}</tbody></table></div></section></section>;
}
