import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { FinanceApiError, financeApi } from "@/client/finance-api";
import type { Asset, Broker } from "@/lib/finance/contracts";
import { AssetSelector } from "./asset-selector";
import { BrokerSelector } from "./broker-selector";

vi.mock("@/client/finance-api", async (load) => {
  const actual = await load<typeof import("@/client/finance-api")>();
  return { ...actual, financeApi: { ...actual.financeApi } };
});

const asset: Asset = { id:"11111111-1111-4111-8111-111111111111", ticker:"ACME3", nome:"Acme", tipo:"ACAO", mercado:"B3", moeda:"BRL", ativo:true, logoProvider:null, logoReference:null };
const broker: Broker = { id:"22222222-2222-4222-8222-222222222222", razaoSocial:"XP Investimentos CCTVM S.A.", nomeFantasia:"XP Investimentos", logoProvider:null, logoReference:null };
function wrapper(children: React.ReactNode) { return <QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}>{children}</QueryClientProvider>; }

describe("seletores operacionais",()=>{
  beforeEach(()=>{vi.restoreAllMocks();vi.spyOn(financeApi,"discoverB3").mockResolvedValue([]);});
  afterEach(cleanup);
  it("oferece o ticker retornado pela discovery publica da B3",async()=>{vi.spyOn(financeApi,"assets").mockResolvedValue({items:[],page:0,size:20,totalElements:0,totalPages:0});vi.spyOn(financeApi,"discoverB3").mockResolvedValue([{ticker:"PETR4",mercado:"B3"}]);vi.spyOn(financeApi,"exactAsset").mockResolvedValue({...asset,ticker:"PETR4"});const onChange=vi.fn();render(wrapper(<AssetSelector value={null} onChange={onChange}/>));await userEvent.type(screen.getByPlaceholderText("Ticker ou nome"),"PET");await userEvent.click(await screen.findByRole("option",{name:/PETR4/}));await waitFor(()=>expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ticker:"PETR4"})));});
  it("seleciona o match canônico exato",async()=>{vi.spyOn(financeApi,"assets").mockResolvedValue({items:[asset],page:0,size:20,totalElements:1,totalPages:1});vi.spyOn(financeApi,"exactAsset").mockResolvedValue(asset);const onChange=vi.fn();render(wrapper(<AssetSelector value={null} onChange={onChange}/>));await userEvent.type(screen.getByPlaceholderText("Ticker ou nome")," acme3 ");await userEvent.click(screen.getByRole("button",{name:"Verificar ticker"}));await waitFor(()=>expect(onChange).toHaveBeenCalledWith(asset));expect(screen.queryByText(/Cadastrar ticker/)).not.toBeInTheDocument()});
  it("oferece cadastro quando há fuzzy sem exato e seleciona ticker renomeado",async()=>{vi.spyOn(financeApi,"assets").mockResolvedValue({items:[asset],page:0,size:20,totalElements:1,totalPages:1});vi.spyOn(financeApi,"exactAsset").mockRejectedValue(new FinanceApiError(404,{status:404,title:"ausente"}));vi.spyOn(financeApi,"registerAsset").mockResolvedValue({...asset,ticker:"BHIA3"});const onChange=vi.fn();render(wrapper(<AssetSelector value={null} onChange={onChange}/>));await userEvent.type(screen.getByPlaceholderText("Ticker ou nome"),"VVAR3");await userEvent.click(screen.getByRole("button",{name:"Verificar ticker"}));await screen.findByText("Cadastrar ticker VVAR3");await userEvent.click(screen.getByRole("button",{name:"Cadastrar ativo"}));await waitFor(()=>expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ticker:"BHIA3"}),"VVAR3 agora é negociado como BHIA3."))});
  it("bloqueia match inativo",async()=>{vi.spyOn(financeApi,"assets").mockResolvedValue({items:[],page:0,size:20,totalElements:0,totalPages:0});vi.spyOn(financeApi,"exactAsset").mockResolvedValue({...asset,ativo:false});render(wrapper(<AssetSelector value={null} onChange={vi.fn()}/>));await userEvent.type(screen.getByPlaceholderText("Ticker ou nome"),"ACME3");await userEvent.click(screen.getByRole("button",{name:"Verificar ticker"}));expect(await screen.findByText(/está inativo/)).toBeVisible()});
  it("preserva o ticker e bloqueia cadastro quando o provedor está indisponível",async()=>{vi.spyOn(financeApi,"assets").mockResolvedValue({items:[],page:0,size:20,totalElements:0,totalPages:0});vi.spyOn(financeApi,"exactAsset").mockRejectedValue(new FinanceApiError(502,{status:502,title:"The financial asset validation service is temporarily unavailable."}));render(wrapper(<AssetSelector value={null} onChange={vi.fn()}/>));const input=screen.getByPlaceholderText("Ticker ou nome");await userEvent.type(input,"ACME3");await userEvent.click(screen.getByRole("button",{name:"Verificar ticker"}));expect(await screen.findByText("Não foi possível validar este ativo agora.")).toBeVisible();expect(screen.getByText(/foi preservado\. Tente novamente em alguns instantes/)).toBeVisible();expect(input).toHaveValue("ACME3");expect(screen.queryByText(/Cadastrar ticker/)).not.toBeInTheDocument();expect(screen.getByRole("button",{name:"Tentar novamente"})).toBeEnabled();expect(document.body).not.toHaveTextContent("The financial asset validation service")});
  it("pagina corretoras, filtra somente as carregadas e mostra vazio",async()=>{vi.spyOn(financeApi,"brokers").mockResolvedValueOnce({items:[broker],page:0,size:20,totalElements:2,totalPages:2}).mockResolvedValueOnce({items:[{...broker,id:"33333333-3333-4333-8333-333333333333",nomeFantasia:"BTG Pactual"}],page:1,size:20,totalElements:2,totalPages:2});render(wrapper(<BrokerSelector value={null} onChange={vi.fn()}/>));expect(await screen.findByRole("option",{name:/XP Investimentos/})).toBeVisible();await userEvent.click(screen.getByRole("button",{name:"Carregar mais"}));expect(await screen.findByRole("option",{name:/BTG Pactual/})).toBeVisible();await userEvent.type(screen.getByPlaceholderText("Filtrar páginas carregadas"),"XP");expect(screen.queryByRole("option",{name:/BTG/})).not.toBeInTheDocument()});
});
