CREATE TABLE corretoras (
    id UUID PRIMARY KEY,
    cnpj CHAR(14) NOT NULL,
    razao_social VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255) NULL,
    cep CHAR(8) NOT NULL,
    logradouro VARCHAR(255) NOT NULL,
    bairro VARCHAR(160) NOT NULL,
    cidade VARCHAR(160) NOT NULL,
    uf CHAR(2) NOT NULL,
    numero VARCHAR(20) NULL,
    complemento VARCHAR(160) NULL,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_corretoras_cnpj UNIQUE (cnpj),
    CONSTRAINT ck_corretoras_cnpj_canonico CHECK (cnpj ~ '^[0-9]{14}$'),
    CONSTRAINT ck_corretoras_cep_canonico CHECK (cep ~ '^[0-9]{8}$'),
    CONSTRAINT ck_corretoras_uf_canonica CHECK (uf ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_corretoras_razao_social CHECK (razao_social = btrim(razao_social) AND razao_social <> ''),
    CONSTRAINT ck_corretoras_nome_fantasia CHECK (nome_fantasia IS NULL OR (nome_fantasia = btrim(nome_fantasia) AND nome_fantasia <> '')),
    CONSTRAINT ck_corretoras_logradouro CHECK (logradouro = btrim(logradouro) AND logradouro <> ''),
    CONSTRAINT ck_corretoras_bairro CHECK (bairro = btrim(bairro) AND bairro <> ''),
    CONSTRAINT ck_corretoras_cidade CHECK (cidade = btrim(cidade) AND cidade <> ''),
    CONSTRAINT ck_corretoras_numero CHECK (numero IS NULL OR (numero = btrim(numero) AND numero <> '')),
    CONSTRAINT ck_corretoras_complemento CHECK (complemento IS NULL OR (complemento = btrim(complemento) AND complemento <> '')),
    CONSTRAINT ck_corretoras_timestamps CHECK (atualizado_em >= criado_em)
);
