package com.carteira.carteiraInvestimento.integration;

import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.carteira.carteiraInvestimento.application.port.UsuarioPort; import com.carteira.carteiraInvestimento.application.service.BrokerLocalTransactionService; import com.carteira.carteiraInvestimento.domain.broker.Corretora; import com.carteira.carteiraInvestimento.domain.identity.*;
import java.sql.*; import java.time.*; import java.util.*; import javax.sql.DataSource;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.*; import org.springframework.security.oauth2.jose.jws.MacAlgorithm; import org.springframework.security.oauth2.jwt.*; import org.springframework.test.web.servlet.MockMvc;
import com.fasterxml.jackson.databind.ObjectMapper;

@AutoConfigureMockMvc @SpringBootTest
class BrokerCatalogSecurityIT extends PostgreSqlContainerSupport {
    @Autowired MockMvc mvc; @Autowired UsuarioPort usuarios; @Autowired JwtEncoder encoder; @Autowired BrokerLocalTransactionService local; @Autowired DataSource dataSource; ObjectMapper mapper=new ObjectMapper();
    Corretora broker;
    @BeforeEach void setup() throws Exception {execute("DELETE FROM logs_auditoria WHERE tipo_evento LIKE 'CORRETORA_%'");execute("DELETE FROM corretoras");broker=local.create(Corretora.nova("19131243000197","XP",null,"01310100","Paulista","Bela Vista","São Paulo","SP",null,null,Clock.systemUTC()),null,UUID.randomUUID());}
    @Test void anonymousGets401AndUserReadsOnlySelectionButCannotMutate() throws Exception {Usuario user=user(Role.ROLE_USER);String token=bearer(user);mvc.perform(get("/api/v1/corretoras")).andExpect(status().isUnauthorized()).andExpect(header().exists("X-Correlation-ID"));mvc.perform(get("/api/v1/corretoras/{id}",broker.id()).header(HttpHeaders.AUTHORIZATION,token)).andExpect(status().isOk()).andExpect(jsonPath("$.cep").doesNotExist());UUID correlation=UUID.randomUUID();mvc.perform(post("/api/v1/corretoras").header(HttpHeaders.AUTHORIZATION,token).header("X-Correlation-ID",correlation).contentType(org.springframework.http.MediaType.APPLICATION_JSON).content("{\"cnpj\":\"19131243000197\"}")).andExpect(status().isForbidden());assertThat(count("SELECT count(*) FROM logs_auditoria WHERE tipo_evento='ACESSO_NEGADO' AND correlation_id='"+correlation+"'")).isEqualTo(1);}
    @Test void inactiveBrokerIsInvisibleToUserAndVisibleToAdmin() throws Exception {Usuario user=user(Role.ROLE_USER),admin=user(Role.ROLE_ADMIN);local.lifecycle(broker.id(),false,admin.id(),UUID.randomUUID());mvc.perform(get("/api/v1/corretoras/{id}",broker.id()).header(HttpHeaders.AUTHORIZATION,bearer(user))).andExpect(status().isNotFound());mvc.perform(get("/api/v1/corretoras/cnpj/{cnpj}",broker.cnpj()).header(HttpHeaders.AUTHORIZATION,bearer(user))).andExpect(status().isNotFound());mvc.perform(get("/api/v1/corretoras").header(HttpHeaders.AUTHORIZATION,bearer(user))).andExpect(jsonPath("$.totalElements").value(0));mvc.perform(get("/api/v1/corretoras/{id}",broker.id()).header(HttpHeaders.AUTHORIZATION,bearer(admin))).andExpect(status().isOk()).andExpect(jsonPath("$.cep").value("01310100"));}
    @Test void nonCanonicalOrInvalidCnpjPathAndInvalidUuidAre400() throws Exception {Usuario user=user(Role.ROLE_USER);for(String value:List.of("19.131.243/0001-97","19131243000198","abc"))mvc.perform(get("/api/v1/corretoras/cnpj/{cnpj}",value).header(HttpHeaders.AUTHORIZATION,bearer(user))).andExpect(status().isBadRequest());mvc.perform(get("/api/v1/corretoras/not-a-uuid").header(HttpHeaders.AUTHORIZATION,bearer(user))).andExpect(status().isBadRequest());}
    @Test void openApiDocumentsExactlySixBrokerOperationsAndNoProviderSchema() throws Exception {String json=mvc.perform(get("/v3/api-docs")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();var paths=mapper.readTree(json).path("paths");int operations=0;var fields=paths.fields();while(fields.hasNext()){var entry=fields.next();if(!entry.getKey().startsWith("/api/v1/corretoras"))continue;for(String method:List.of("get","post","patch","put","delete"))if(entry.getValue().has(method))operations++;assertThat(entry.getValue().has("delete")).isFalse();}assertThat(operations).isEqualTo(6);assertThat(json).doesNotContain("CnpjProviderResponse","CvmProviderResponse","ViaCepProviderResponse").contains("422","502","BrokerSelectionResponse","BrokerAdminResponse");}
    private Usuario user(Role role){return usuarios.save(Usuario.novoUsuario("Broker Test","broker-"+UUID.randomUUID()+"@example.test","hash",role));}
    private String bearer(Usuario u){Instant now=Instant.now();JwtClaimsSet c=JwtClaimsSet.builder().subject(u.id().toString()).claim("role",u.role().name()).issuedAt(now).expiresAt(now.plusSeconds(3600)).id(UUID.randomUUID().toString()).issuer("carteira-investimento-backend").audience(List.of("carteira-investimento-api")).build();return "Bearer "+encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),c)).getTokenValue();}
    private void execute(String sql)throws Exception{try(Connection c=dataSource.getConnection();Statement s=c.createStatement()){s.executeUpdate(sql);}}
    private long count(String sql)throws Exception{try(Connection c=dataSource.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){r.next();return r.getLong(1);}}
}
